app/__init__.py
from flask import Flask
from app.config import Config

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    # Initialize Flask extensions here

    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.recommedations import bp as recommedations_bp
    app.register_blueprint(recommedations_bp, url_prefix='/recommedations')

    from app.users import bp as users_bp
    app.register_blueprint(users_bp, url_prefix='/users')
    

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask_login import login_required
from app.main import bp
from flask import Response, flash, redirect, render_template, request, session, url_for

from app.main.camera import VideoCamera
from app.main.songs import get_song
from ..recommedations.spotify_auth import SpotifyAPI


video_stream = VideoCamera()

@login_required
@bp.route('/')
def home():
    if 'username' in session:
        user = session.get('username')
        s_api = SpotifyAPI()
        token = s_api.get_token()
        session['token'] = token
        cam_status = video_stream.off_camera()
        return render_template('camera.html',cam_status=cam_status, user=user)
    else:
        # flash('Log In First', 'danger')
        return redirect(url_for('users.login'))

def gen(camera):
    while True:
        frame= camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@bp.route('/video_feed')
def video_feed():
     return Response(gen(video_stream),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


@bp.route('/requests',methods=['POST','GET'])
def tasks():
    if request.method == 'POST':
        if request.form.get('start') == 'Start':
            cam_status= video_stream.on_camera()
            return render_template('camera.html',cam_status=cam_status)
        elif request.form.get('stop') == 'Stop':
            cam_status = video_stream.off_camera()
            return render_template('camera.html',cam_status=cam_status)
        
        elif request.form.get('capture') == 'Capture':
            cam_status = video_stream.off_camera()
            emotion = video_stream.get_detected_emotion()
            session['emotion'] = emotion
            return redirect(url_for('recommendations.recommend'))
    # Add a return statement to return an empty string for the GET request
        
@bp.route('/about')
def about():
        if 'username' in session:
            user = session.get('username')
            return render_template('about.html', user=user)
        else:
            flash('Log in First', 'danger')
            return redirect(url_for('users.login'))

app/recommedations/__init__.py
from flask import Blueprint

bp = Blueprint('recommendations', __name__)

from app.recommedations import routes

app/recommedations/routes.py
import json
from app.recommedations import bp
from flask import Response, redirect, render_template, request, session, url_for
from app.main.songs import get_song
from app.static.FER_recom.cs_rec import ContentBasedRecommender
from app.static.FER_recom.knn_rec import KNNRecommender
from app.static.FER_recom.svd_rec import SVDRecommend
from ..recommedations.spotify_auth import SpotifyAPI
import requests



cs = ContentBasedRecommender()
knn = KNNRecommender()
svd = SVDRecommend()



@bp.route('/', methods=['POST','GET'])
def recommend():
    user = session.get('username')
    print(user)
    s_api = SpotifyAPI()
    token = session.get('token')
    emotion = session.get('emotion')
    songs = get_song(emotion,user)
    ids = songs['SongID'].tolist()
    ids = ','.join(ids)
    song_details = s_api.get_tracks(token, ids)
#     print(song_details)
    if request.method == 'POST':
        song_id = request.form['song_name']
        cs_songs = cs.recommender(user_id=user,recommendation={"SongID": song_id,"number_songs": 5 })
        cs_ids = []
        for x in cs_songs:
                cs_ids.append(x[3])
        cs_ids = ','.join(cs_ids)
        cs_songs_details = s_api.get_tracks(token, cs_ids)
        ibcf_songs = knn.recommender(song_id=song_id)
        ibcf_ids = []
        for x in ibcf_songs:
                ibcf_ids.append(x['song_id'])
        ibcf_ids = ','.join(ibcf_ids)
        ibcf_songs_details = s_api.get_tracks(token, ibcf_ids)
        user_id_no = int(user[4:])
        ubcf_songs = svd.recommender(user=user_id_no, nosong =5)
        ubcf_ids = []
        for x in ubcf_songs:
                ubcf_ids.append(x['song_id'])
        ubcf_ids = ','.join(ubcf_ids)
        ubcf_songs_details = s_api.get_tracks(token, ubcf_ids)
        return render_template('songs.html', emotion=emotion, song_id=song_id, cs_songs=cs_songs_details, ibcf_songs=ibcf_songs_details, ubcf_songs=ubcf_songs_details, user= user)
    return render_template('songs.html', songs=song_details, emotion=emotion, user = user)

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from app.users import routes

app/users/routes.py
from app.users import bp
from flask import flash, redirect, render_template, request, session, url_for
import pandas as pd


user_data = pd.read_csv('app/static/user_data.csv')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user_row = user_data[(user_data['UserName'] == username)]
        # Dummy authentication, replace with your own authentication logic
        if not user_row.empty and password == 'admin':
            session['username'] = username
            # Redirect to a different page after successful login
            return redirect(url_for('main.home'))
        else:
            flash('Invalid username or password', 'danger')
            return render_template('login.html')
            
    
    # Render login form template for GET requests
    return render_template('login.html')

@bp.route('/logout')
def logout():
    session.pop('username', None)
    flash('Login to Continue', 'secondary')

    return redirect(url_for('users.login'))

app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row align-items-center justify-content-between">
      <div class="col-md-12">
        <div class="p-5">
          <h5 class="text-uppercase" style="color: #1db954;">Hello {{user}}</h5>
        <h1 class="mb-4 display-4" style="font-weight: 600;">Welcome to <span style="color: #1db954;">Moodify</span></h1>
        <p class="text-white" style="line-height: 2;">
            Our GUI web application seamlessly integrating Facial Emotion Recognition technology with music recommendation systems. Whether you seek to uplift your mood, explore new musical territories, or simply indulge in a tailored listening experience, our app offers a dynamic and personalized journey through the realms of emotion and music. Join us on this exciting exploration at the intersection of technology, emotion, and music. Experience the power of Facial Emotion Recognition in music recommendation systems with our intuitive and feature-rich GUI web app today!
        </P>
        <ul>
            <li>
                <strong>Facial Emotion Detection:</strong> Our app utilizes YOLOv8 to accurately identify and interpret facial expressions in real-time, allowing users to interact with music based on their current emotional state.
            </li>
            <li>
                <strong>Personalized Music Recommendations:</strong> Drawing upon various algorithms, our app recommends songs that resonate with the detected emotions. It first showcases the top favorite songs associated with the detected emotion, providing users with an instant selection of mood-appropriate music.
            </li>
            <li>
                <strong>"Your Favourites" Suggestions:</strong> Upon selecting a song of interest, our app offers a curated list of top 5 similar songs, allowing users to explore related tracks that align with their musical preferences. This is done using the Cosine Similarity algorithm.
            </li>
            <li>
                <strong>"Currently Popular" Suggestions:</strong> Our app suggests five songs that are popular among users with similar listening profiles. This is done using the K-Nearest Neighbour algorithm algorithm.
            </li>
            <li>
                <strong>"Discover New" Suggestions:</strong> For added variety, our app also presents random popular songs that are favored by users with similar listening profiles, ensuring a diverse and engaging listening experience. This is done using the Singular Value Decomposition.
            </li>
        </ul>
                
        </div>
      </div>
    </div>

  
  
{% endblock content %}

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Flask app</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}" 
</head>

<body>
  <nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('main.home') }}">Moodify</a>
      <!-- Right-aligned buttons -->
      <div class="ml-auto">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" >
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          {% if 'username' in session %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.home') }}"> {{user}}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
          </li>
          {% endif %}
          
        </ul>
      </div>
      </div>
    </div>
  </nav>

  {% block content %}

  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

app/templates/camera.html
{% extends 'base.html' %}

{% block content %}
<h1 class="home-title">Song Reccomendations by Moodify</h1>
<div class="container">
    <div class="row">
        <div class="camera-controls">
            <form method="post" action="{{ url_for('main.tasks') }}">
                <input type="submit" class="btn btn-primary my-button" value="Start" name="start" />
                <input type="submit" class="btn btn-primary my-button" value="Stop" name="stop" />
                <input type="submit" class="btn btn-primary my-button" value="Capture" name="capture" />
            </form>
            <img src="{{ url_for('main.video_feed') }}" onerror="this.style.display='none'" class="camera-feed" />
            {% if cam_status == False %}
            <div class="alert alert-secondary" role="alert">
                Camera is currently turned off, click on 'Start' to get song recommendations
              </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content%}

app/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="flex-parent">
        <div class="left">
            <div class="overlay">
            <h1>Moodify.</h1>
            <p>Welcome to Moodify - Where Your Emotions Meet Melodies! Let's Tune Into Your Mood and Discover Your Perfect Playlist!</p>
            </div>
        </div>
            <div class="right">
                <form method="POST">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <label for="username">Username:</label><br>
                    <input type="text" id="username" name="username" required><br>
                    <label for="password">Password:</label><br>
                    <input type="password" id="password" name="password" required><br>
                    <button type="submit">Login</button>
                </form>
        </div>
    </div>
{% endblock content %}

app/templates/songs.html
{% extends 'base.html' %}
{% block content %}
{% if songs %}
    <ul>
            <div class="spotify-playlists-1">
                <h2>Your Top Songs for the Mood: {{emotion}}</h2>
            <form method="post" action="{{ url_for('recommendations.recommend') }}">
            {% for i in range(0,songs['id']|length)%}
                    <div class="list2">
                      <div class="item">
                        {% set song_image = songs['images'][i] %}
                            {% if song_image and song_image != '/' %}
                                <!-- The song_image variable contains a valid path to the image -->
                                <img src="{{ song_image }}" />
                            {% else %}
                                <!-- Use the default image path -->
                                <img src="{{ url_for('static', filename='images/login-img.jpg') }}" />
                            {% endif %}
                        <div class="play">
                            <span class="fa fa-play">
                                <button type="submit" class="btn song-button" name="song_name" value="{{ songs['id'][i] }}"> 
                                </button>
                            </span>
                          </div>
                        <h4 title="{{songs['names'][i]}}">{{ songs['names'][i] }}</h4>
                        {% set num_artists = songs['artists'][i]|length  + 1%}
                        {% for artist in songs['artists'][i] %}
                            <span>{{ artist }}{% if not loop.last and loop.index != num_artists - 1 %},{% endif %}</span>
                        {% endfor %}
                        
                      </div>
            {% endfor %}
        </form>
    </ul>
{% endif %}
{% if song_id %}
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <div class="spotify-iframe-container">
            <iframe class="spotify-iframe"
                src="https://open.spotify.com/embed/track/{{song_id}}?utm_source=generator&theme=0" width="100%"
                height="152" frameBorder="0" allowfullscreen=""
                allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
                loading="lazy"></iframe>
        </div>
    </div>
</div>

{% endif %}

<div class="container text-center">
    <div class="row">
        <div class="col">
            {% if cs_songs %}
            <ul>
                <div class="spotify-playlists">
                    <h2>Your Favorites for Mood: {{emotion}}</h2>
                <form method="post" action="{{ url_for('recommendations.recommend') }}">
                {% for i in range(0,cs_songs['id']|length )%}
                        <div class="list">
                          <div class="item">
                            {% set song_image = cs_songs['images'][i] %}
                            {% if song_image and song_image != '/' %}
                                <!-- The song_image variable contains a valid path to the image -->
                                <img src="{{ song_image }}" />
                            {% else %}
                                <!-- Use the default image path -->
                                <img src="{{ url_for('static', filename='images/login-img.jpg') }}" />
                            {% endif %}
                            <div class="play">
                                <span class="fa fa-play">
                                    <button type="submit" class="btn song-button" name="song_name" value="{{ cs_songs['id'][i] }}"> </button>
                                </span>
                              </div>
                            <h4 title="{{cs_songs['names'][i]}}">{{ cs_songs['names'][i] }}</h4>
                            {% set num_artists = cs_songs['artists'][i]|length  + 1%}
                            {% for artist in cs_songs['artists'][i] %}
                                <span>{{ artist }}{% if not loop.last and loop.index != num_artists - 1 %},{% endif %}</span>
                            {% endfor %}
                            
                          </div>
                        
                {% endfor %}
            </form>
        </ul>
            {% endif %}
        </div>
        <div class="col">
            {% if ibcf_songs %}
            <ul>
                <div class="spotify-playlists">
                    <h2>Currently Popular in Mood: {{emotion}}</h2>
                <form method="post" action="{{ url_for('recommendations.recommend') }}">
                {% for i in range(0,ibcf_songs['id']|length)%}
                        <div class="list">
                          <div class="item">
                            {% set song_image = ibcf_songs['images'][i] %}
                            {% if song_image and song_image != '/' %}
                                <!-- The song_image variable contains a valid path to the image -->
                                <img src="{{ song_image }}" />
                            {% else %}
                                <!-- Use the default image path -->
                                <img src="{{ url_for('static', filename='images/login-img.jpg') }}" />
                            {% endif %}
                            <div class="play">
                                <span class="fa fa-play">
                                    <button type="submit" class="btn song-button" name="song_name" value="{{ ibcf_songs['id'][i] }}"> </button>
                                </span>
                              </div>
                            <h4 title="{{ibcf_songs['names'][i]}}">{{ ibcf_songs['names'][i] }}</h4>
                            {% set num_artists = ibcf_songs['artists'][i]|length  + 1%}
                            {% for artist in ibcf_songs['artists'][i] %}
                                <span>{{ artist }}{% if not loop.last and loop.index != num_artists - 1 %},{% endif %}</span>
                            {% endfor %}
                            
                          </div>
                {% endfor %}
            </form>
        </ul>
            {% endif %}
        </div>
        <div class="col">
            {% if ubcf_songs %}
            <ul>
                <div class="spotify-playlists">
                    <h2>Discover New</h2>
                <form method="post" action="{{ url_for('recommendations.recommend') }}">
                {% for i in range(0,ubcf_songs['id']|length)%}
                        <div class="list">
                          <div class="item">
                            {% set song_image = ubcf_songs['images'][i] %}
                            {% if song_image and song_image != '/' %}
                                <!-- The song_image variable contains a valid path to the image -->
                                <img src="{{ song_image }}" />
                            {% else %}
                                <!-- Use the default image path -->
                                <img src="{{ url_for('static', filename='images/login-img.jpg') }}" />
                            {% endif %}
                            <div class="play">
                                <span class="fa fa-play">
                                    <button type="submit" class="btn song-button" name="song_name" value="{{ ubcf_songs['id'][i] }}"> </button>
                                </span>
                              </div>
                            <h4 title="{{ubcf_songs['names'][i]}}">{{ ubcf_songs['names'][i] }}</h4>
                            {% set num_artists = ubcf_songs['artists'][i]|length  + 1%}
                            {% for artist in ubcf_songs['artists'][i] %}
                                <span>{{ artist }}{% if not loop.last and loop.index != num_artists - 1 %},{% endif %}</span>
                            {% endfor %}
                            
                          </div>
                {% endfor %}
            </form>
        </ul>
            {% endif %}
        </div>
    </div>
</div>


{% endblock content %}